# サイト基本情報
title: YangGen的补给站
subtitle: ''
description: ''
author: Yangtaiyu
language: zh-CN
timezone: Asia/Shanghai

# URL設定
url: https://bbs8rtknbw-cloud.github.io
root: /yasu123/   # GitHub Pages のサブディレクトリ

# ディレクトリ
source_dir: source
public_dir: public

# プラグイン
plugins:
  - hexo-generator-search
  - hexo-generator-feed

# Markdownやハイライトの設定
markdown:
  render:
    html: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
